### Применим наши знания на настоящих данных

Будем классифицировать ранее подготовленный датасет пассажиров с титаника

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Загрузка данных
data = pd.read_csv('..\9_2\Titanic-Dataset-Processed-1.csv')

data

,Survived,Age,SibSp,Parch,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_male,Embarked_C,...,Embarked_S,G,F,C,T,B,Unknown,D,E,A
0,0,22.000000,1,0,7.2500,False,False,True,True,False,...,True,False,False,False,False,False,True,False,False,False
1,1,38.000000,1,0,71.2833,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
2,1,26.000000,0,0,7.9250,False,False,True,False,False,...,True,False,False,False,False,False,True,False,False,False
3,1,35.000000,1,0,53.1000,True,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,0,35.000000,0,0,8.0500,False,False,True,True,False,...,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.000000,0,0,13.0000,False,True,False,True,False,...,True,False,False,False,False,False,True,False,False,False
887,1,19.000000,0,0,30.0000,True,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False
888,0,29.699118,1,2,23.4500,False,False,True,False,False,...,True,False,False,False,False,False,True,False,False,False
889,1,26.000000,0,0,30.0000,True,False,False,True,True,...,False,False,False,True,False,False,False,False,False,False
890,0,32.000000,0,0,7.7500,False,False,True,True,False,...,False,False,False,False,False,False,True,False,False,False

In [3]:
#Разделение данных на признаки и целевую переменную
X = data.drop('Survived', axis=1)
y = data['Survived']

#Разделение данных на обучающую и тестовую выборки
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [4]:
#Посмотрим на метрики при случайном предсказании
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier(strategy="uniform")
dummy_clf.fit(X_train, y_train)

dummy_clf.score(X_test, y_test)

0.5335820895522388

In [5]:
#Посмотрим на метрики при предсказании одним классом (наибольшим)
dummy_clf = DummyClassifier(strategy="most_frequent")
dummy_clf.fit(X_train, y_train)

dummy_clf.score(X_test, y_test)

0.585820895522388

In [6]:
#Попробуем обучить модель к ближайших соседей
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

#Получение прогнозов
y_pred = knn.predict(X_test)

#Оценка качества модели
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.6902985074626866

In [7]:
#Поэкспериментируем с количеством соседей
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(f"количество соседей: 1, точность: {accuracy_score(y_test, y_pred)}")

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(f"количество соседей: 3, точность: {accuracy_score(y_test, y_pred)}")

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(f"количество соседей: 7, точность: {accuracy_score(y_test, y_pred)}")

knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(f"количество соседей: 9, точность: {accuracy_score(y_test, y_pred)}")

количество соседей: 1, точность: 0.6977611940298507
количество соседей: 3, точность: 0.6940298507462687
количество соседей: 7, точность: 0.7126865671641791
количество соседей: 9, точность: 0.6977611940298507

In [9]:
#Попробуем обучить модель логистической регрессии
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)

accuracy_score(y_test, y_pred)

0.8059701492537313

In [34]:
#Попробуем обучить модель градиентного бустинга - лучшей классической модели для табличных данных
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(learning_rate=1, max_depth=1,)
gb.fit(X_train, y_train)

y_pred = gb.predict(X_test)

accuracy_score(y_test, y_pred)

0.8246268656716418